### ISSUE TITLE
[Certification] 2017 Qual-E Testcase Issue

### ISSUE THREAD

**Issue by LGelectronics** [youtube/js_mse_eme#15]
URL : https://2017-dot-qual-e.appspot.com/  
1. Progressive test
Certification requirements :  Must pass tests #1-25
-> This case is not worked, stop no.15
-> It's same to Chrome browser
-> Please check it
2. MSE Test
-> 72. AppendH264VideoOutOfOrder fail
-> It's same to Chrome browser and canary (m55)
-> Please check it

**Comment by tdedecko** [comment]
Progressive tests on tip have been fixed in: https://github.com/youtube/js_mse_eme/commit/8cb8c5342d2a0287da2165e05e324ca6e2eb4e93

AppendH264VideoOutOfOrder on tip has been made optional in:
https://github.com/youtube/js_mse_eme/commit/c2d8fb5ffeeb55285e5b36520c2751b771e10f4f
