### ISSUE TITLE
MSE Test : 12. AddsourceBuffer 

### ISSUE THREAD

**Issue by LGelectronics** [youtube/js_mse_eme#16]
The testcase of AddsourceBuffer is changed a few days ago.
(audio/mp4, mp4a.40.2 -> audio/webm, opus)
LG TV is not supported opus codec. 
So We get the fail.
Is there any chance of changing to AAC??

**Comment by tdedecko** [comment]
Opus has been made optional and AddSourceBuffer test now checks AAC. See: https://github.com/youtube/js_mse_eme/commit/54d514b06b5f8b333c3ce119f5357cfe4b99f43a

These changes will be pushed out later this week.
