### ISSUE TITLE
Abnormal behavior in 2016 EME Conformance tests

### ISSUE THREAD

**Issue by gihwankim** [youtube/js_mse_eme#19]
(v 20161104093450 )
Hi,
I tested EME for youtube certificate, but there are abnormal behavior. 
When I press Enter something, but RunAll has started always . maybe there are some bugs in 11/4 version.
So , I want to test only that failed but I can't.

Even MSE test is same .

please revise this issue. 

thanks.

**Comment by seoz** [comment]
Thanks for the report.

Thom, it looks live js/harness/compactTestView.js is different from that of github's one.
Live compactTestView.js has 'keydown' event listener and it caused this problem.
Please remove it.

    document.addEventListener('keydown', function(e) {
      if (e.keyCode == 0x0D) {
        if (self.onrunselected) {
          self.onrunselected.call(self, e);
        }
      }
    });

**Comment by tdedecko** [comment]
Thanks for the report. The change has been reverted.
