### ISSUE TITLE
Race condition in MediaSourceDuration tests

### ISSUE THREAD

**Issue by ntrrgc** [youtube/js_mse_eme#28]
MediaSourceDuration tests first append a 1 MB chunk of audio, then **without waiting for it to complete**, calls `appendVideo()`:

```
    var audioXhr = runner.XHRManager.createRequest(audioStream.src,
        function(e) {
      var audioContent = audioXhr.getResponseData();
      audioSb.appendBuffer(audioContent);
      appendVideo();
    });
```

`appendVideo()` then appends the video initialization segment and 10 seconds worth of video. Then calls `setDuration()`.

```
    var appendVideo = function() {
      runner.assert(isNaN(media.duration), 'Initial media duration not NaN');
      media.play();
      appendInit(media, videoSb, videoChain, 0, function() {
        appendUntil(runner.timeouts, media, videoSb, videoChain, 10,
            function() {
          setDuration(5, ms, [videoSb, audioSb], function() {
```

But this is wrong: At that point you still have no guarantee that the audio append has finished successfully, and changing the duration of a `MediaSource` requires that none of its `SourceBuffer`s is still updating. This may seem unlikely as it's racing against an XHR download and two other appends, but I have seen it happening a lot. It was causing `InvalidStateError`s to be thrown.

I could confirm this by adding a log line:
```
        appendUntil(runner.timeouts, media, videoSb, videoChain, 10,
          function() {
            self.log(`appended first 10s of video, updatingVideo=${videoSb.updating} updatingAudio=${audioSb.updating}`);
```

Indeed, updatingAudio was still true, and soon after, the duration change failed. After modifying the test to call `appendVideo()` only after the audio append has finished, the problem was fixed.

**Comment by tdedecko** [comment]
Thanks for this bug report. I'll work on a fix.

**Comment by tdedecko** [comment]
This should be fixed with the latest change.

**Comment by ntrrgc** [comment]
Looks good to me, thank you!
