### ISSUE TITLE
2016 EME test issue

### ISSUE THREAD

**Issue by psivasubramanian** [youtube/js_mse_eme#30]
I'm observing this error while running PlayReadyH264Video/PlayReadyAacAudio EME tests (YouTube 2016) on WPE browser on HiKey board.

https://yt-dash-mse-test.commondatastorage.googleapis.com/unit-tests/js/harness/main-20180216110138.js:123:16: CONSOLE LOG onNeedKey() 
https://yt-dash-mse-test.commondatastorage.googleapis.com/unit-tests/js/lib/eme/encryptedMediaPortability-20180216110138.js:202:19: CONSOLE ERROR TypeError: First argument should be an object

This is because of code https://github.com/youtube/js_mse_eme/blob/master/js/lib/eme/2016/emeManager.js#L88, instead should it be "initData = addBMFFClearKeyID(e.initData, this.licenseManager.kids)" ?

**Comment by tdedecko** [comment]
You shouldn't be hitting this part of the code for playready. Likely your media stack is not parsing the initData correctly.
