### ISSUE TITLE
Question regarding car-audio-1MB-trunc.mp4

### ISSUE THREAD

**Issue by estobbart** [youtube/js_mse_eme#33]
car-audio-1MB-trunc.mp4 is 1048576 bytes.
The last mdat @ 955849 claims it's size is 157253, but theres only 92727 bytes left to read.
I'm assuming this is intentional due to the file name being `trunc` but whats the expected behavior of the browser? That part seems unclear.

**Comment by jiaqzhao** [comment]
Hi, where or which test specifically are you referring to?

**Comment by estobbart** [comment]
It wasn't really specific to a test, it looks like the content is used in a number of places.

**Comment by jiaqzhao** [comment]
It's used in multiple places, so the expected behavior would depend on the test.

**Comment by estobbart** [comment]
Reverse engineering it... it looks like it's supposed to take the trun box, and determine how many full samples it has based on the mdat size and then modify the duration of the segment accordingly. Could you confirm that?

**Comment by jiaqzhao** [comment]
The primary reason to truncate this audio file is to have it be ~1MB, so I don't think much work was done or considered besides truncating the file, but it's true that we could have modify the duration accordingly.

**Comment by estobbart** [comment]
Ah ok, interesting point about the ~1mb. In general is supporting truncated content like this part of any YouTube certification? Like if network drops prior to a segment completing the download, will the YouTube player append to the buffer whatever it has obtained?

**Comment by jiaqzhao** [comment]
There's no specific requirement regarding supporting truncated content, but there are requirements on network stack, please check our technical requirement for more details. The YouTube player should append to the buffer whatever it has obtained.

**Comment by estobbart** [comment]
Thank you for your help @jiaqzhao
