### ISSUE TITLE
Audio Context is not closed after test fails/succeeds

### ISSUE THREAD

**Issue by woutermeek** [youtube/js_mse_eme#34]
We're trying to run the MSE Conformance tests in a loop. We've noticed that the audio context on some test cases are not closed properly, thus slowly requesting more resources of the device.

[this](https://github.com/youtube/js_mse_eme/blob/master/js/tests/2018/conformanceTest.js#L1702-L1710) method should close the context once it is done. 

ctx.close(); after runner.succeed() should do the trick.

**Comment by jiaqzhao** [comment]
Thanks for reporting, I will take a look.

**Comment by jiaqzhao** [comment]
This should be fixed as of [079f3b9](https://github.com/youtube/js_mse_eme/commit/079f3b937f7eea0ce0736788e00607ca0cdb6f5e)
