### ISSUE TITLE
This test does not take into account devices with long pre-roll.

### ISSUE THREAD

**Issue by m-zdun** [youtube/js_mse_eme#35]
https://github.com/youtube/js_mse_eme/blob/7e0b921d3f6c4c311679d31cce13f2e3dd69abb2/js/tests/2019/conformanceTest.js#L535

This line, on devices using Chromium with long video pre-roll, will result in couple of `timeupdate` events synthesized before any current time update actually comes from underlying native player. This results in `baseTimeDiff` with little connection to actual time update reporting. And since the test looks for worst delta against wall-clock, all actual changes in PTS may appear to have it rather big, no matter how stable reporting actually is.

One way to account for pre-roll might be to ignore for the synthesized events with

```js
if (video.currentTime === 0.0)
  return;

baseTimeDiff = util.ElapsedTimeInS() - video.currentTime;
```

and getting the baseline at the first non-zero time reported by the player.

**Comment by jiaqzhao** [comment]
This might be a chrome bug, created [this](https://bugs.chromium.org/p/chromium/issues/detail?id=868092) if you want to follow along.
