### ISSUE TITLE
Determinig supportsVideoPerformanceMetrics issue

### ISSUE THREAD

**Issue by woutermeek** [youtube/js_mse_eme#36]
[This](https://github.com/youtube/js_mse_eme/blob/master/lib/mse/videoPerformance.js#L27-L29) code should determine wether the browser supports these type of metrics or not. This if statement returns the wrong value if both getVideoPlaybackQuality and (webkitDecodedFrameCount, webkitDroppedFrameCount) are supported. In case of both being there it should also return true.

I'm trying to run these tests at the moment with a browser which supports both, and I'm not able to because of this.

**Comment by jiaqzhao** [comment]
Thanks for pointing this out, it's been fixed in the recent commits.
