### ISSUE TITLE
Move HFR media files of Playback Performance tests into their own test group

### ISSUE THREAD

**Issue by whimboo** [youtube/js_mse_eme#38]
A couple of the 60fps media files especially for testing the playback rate are already listed under the `HFR Playback Rate Performance` test group, but some are still part of the `Playback Performance` test group.

It would be great to have the 60fps media files always under their own section. As such could the remaining ones from `Playback Performance` be moved to `HFR Playback Performance`? Also having all 60fps media files available for 1x playback rate would be fantastic.

CC'ing @PhilHarnish with whom we discussed the usage of those tests in our CI for Firefox development.

**Comment by jiaqzhao** [comment]
Sorry for the late reply. We have made significant changes to the Playback Performance test suite in 2020/master (coming soon), and so we decided to leave 2019 as it is. I'm going to close this issue and the associated pull request, but feel free to include this in your dev environment. Thanks for the suggestion and helping to make this better.

**Comment by whimboo** [comment]
No problem at all! We will have a look at the 2020 branch when that year comes close, and if there is still something for improvements we will let you know. Thanks!
