### ISSUE TITLE
Allow ranges for test selection

### ISSUE THREAD

**Issue by whimboo** [youtube/js_mse_eme#40]
All test selection related options like `tests`, and `exclude` should accept a range of tests. This would help a lot in reducing the amount of values to give for eg. running all `Playback Performance` tests:

Currently: https://ytlr-cert.appspot.com/2019/main.html?test_type=playbackperf-test&raptor=true&command=run:3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20

Proposal: https://ytlr-cert.appspot.com/2019/main.html?test_type=playbackperf-test&raptor=true&command=run:3-20

Also allowing individual chunks would be nice:

Proposal: https://ytlr-cert.appspot.com/2019/main.html?test_type=playbackperf-test&raptor=true&command=run:3-20,34,81-89

**Comment by jiaqzhao** [comment]
Please checkout [this commit] in 2019, will merge to master later.(https://github.com/youtube/js_mse_eme/commit/ac486eccd4946563827e251fd33c72f2a8c3caf7)

**Comment by whimboo** [comment]
@jiaqzhao this is amazing news! Thanks for adding the range feature for selecting the tests! Do you know when this will be available on the [live site](https://ytlr-cert.appspot.com/2019/main.html?test_type=playbackperf-test)? We were told to get the latest source from there instead of this repository. But maybe we should rely on the latest code as landed on the 2019 branch?

**Comment by jiaqzhao** [comment]
I believe this is available on the live site too.

**Comment by whimboo** [comment]
It actually is, thanks!
