### ISSUE TITLE
Question about MSE Codec tests MediaSourceDuration

### ISSUE THREAD

**Issue by jeunder** [youtube/js_mse_eme#46]
In MSE Codec tests MediaSourceDuration item, I have a question about test function
https://github.com/youtube/js_mse_eme/blob/master/media/mseCodecTest.js#L855
Why it uses checkEq?
Why not uses checkApproxEq as previous line to do the check?

**Comment by austin226** [comment]
Fixed in 9edb3984f98a37ccf6620bd59d4e83eba8fc23a4
