### ISSUE TITLE
Update the archive for "Download-Media-files" section

### ISSUE THREAD

**Issue by marianrai** [youtube/js_mse_eme#47]
Hello,

The archive that can be downloaded from "Download-Media-files" section is very old, back from October 20th 2018. A lot of videos are missing.
Can someone update the archive / URL ?
Can you also check if the "Download-Source" reflects the last 2020 updates ?

Thank you!

**Comment by JiashengYang** [comment]
Hello, 

We've updated the zip media file and it is now up-to-date.
Thanks for filing this request.
