### ISSUE TITLE
The dot from the test names has been removed

### ISSUE THREAD

**Issue by marianrai** [youtube/js_mse_eme#48]
Hello,

Is there a plan to add back the dot for test names ?
On 2019 branch there was something like : PlaybackPerf.H264.1080p30@2X
On 2020 : PlaybackPerfH2641080p30@2X

Now it's harder to read.

Thank you!

**Comment by whimboo** [comment]
@austin226 maybe this was done by accident?

**Comment by jiaqzhao** [comment]
Sorry for the late reply. This is added back in [this commit](https://github.com/youtube/js_mse_eme/commit/8cbcaa5ad30182bb8f072c60e2e61ab6e9440dab)
