### ISSUE TITLE
Detailed readme

### ISSUE THREAD

**Issue by harishnb** [youtube/js_mse_eme#49]
Where can I find a detailed readme which has instructions for :
1) downloading complete repo + submodules
2) executing steps
3) The results expected.

**Comment by jiaqzhao** [comment]
We don't have a detailed readme. Hope the following helps.
1. We just removed the use of submodules, but for using submodules, you could follow the official guide from GitHub. To download the repo, you can either download the zip from GitHub or use git clone.
2. You need to host it from your server, and setup the media files, we do not provide such in GitHub at the moment. After this setup, you just need to navigate through the test suite of interest and either click "Run All" or individual test.
3. Test results may vary from different devices, but we try take into device capabilities into account, and so all tests are expected to pass.

**Comment by harishnb** [comment]
Sorry to reopen,  in the main.html I commented the JS which are not present and the page was up without error.  Can you please provide path to the media's so that I can test.
