### ISSUE TITLE
EME 2021 test 22 is loading an incorrect file

### ISSUE THREAD

**Issue by calvaris** [youtube/js_mse_eme#51]
As you can see in this ![screenshot](https://user-images.githubusercontent.com/1021526/102601063-f24f3180-411f-11eb-92aa-762f6424b1b9.png), test 22 fails because it creates a source buffer for video/webm and feeds an mp4 file.

**Comment by calvaris** [comment]
Same problem with test 38, source buffer for video is opened with `video/webm; codecs="vp09.00.51.08"` and loaded file is the same, mp4.

**Comment by jiaqzhao** [comment]
Hi and sorry for the late reply. That's actually intended, the test steam is in mp4 container, the test is failing because of a typo, please expect a new release with the fix in the coming weeks. We will also update this repo.
